server:
  port: 8123

eureka:
  instance:
    hostname: eureka
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka


spring:
  application:
    name: RandomNumberGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: RandomNumberService
        uri: lb://RandomNumberService
        predicates:
          - Method=GET


# No Eureka Server
#spring:
#  cloud:
#      routes:
#        - id: RandomNumberService
#          uri: http://localhost:8082
#          predicates:
#            - Method=GET


logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG